-- ============================================================================
-- 3. INSERTS PARA TABELAS DE REFERÊNCIA
-- ============================================================================

-- Inserindo Tipos de Sensor
INSERT INTO GS_WW_TIPO_SENSOR (NOME_TIPO, DESCRICAO, UNIDADE_MEDIDA, VALOR_MIN, VALOR_MAX) 
VALUES ('UMIDADE_SOLO', 'Sensor de umidade do solo', '%', 0, 100);

INSERT INTO GS_WW_TIPO_SENSOR (NOME_TIPO, DESCRICAO, UNIDADE_MEDIDA, VALOR_MIN, VALOR_MAX) 
VALUES ('TEMPERATURA_AR', 'Sensor de temperatura do ar', '°C', -20, 60);

INSERT INTO GS_WW_TIPO_SENSOR (NOME_TIPO, DESCRICAO, UNIDADE_MEDIDA, VALOR_MIN, VALOR_MAX) 
VALUES ('PLUVIOMETRO', 'Medidor de precipitação', 'mm', 0, 500);

INSERT INTO GS_WW_TIPO_SENSOR (NOME_TIPO, DESCRICAO, UNIDADE_MEDIDA, VALOR_MIN, VALOR_MAX) 
VALUES ('NIVEL_AGUA', 'Sensor de nível de água', 'm', 0, 10);

INSERT INTO GS_WW_TIPO_SENSOR (NOME_TIPO, DESCRICAO, UNIDADE_MEDIDA, VALOR_MIN, VALOR_MAX) 
VALUES ('PH_SOLO', 'Medidor de pH do solo', 'pH', 0, 14);

INSERT INTO GS_WW_TIPO_SENSOR (NOME_TIPO, DESCRICAO, UNIDADE_MEDIDA, VALOR_MIN, VALOR_MAX) 
VALUES ('CONDUTIVIDADE', 'Sensor de condutividade elétrica', 'µS/cm', 0, 5000);

-- Inserindo Níveis de Severidade
INSERT INTO GS_WW_NIVEL_SEVERIDADE (CODIGO_SEVERIDADE, DESCRICAO_SEVERIDADE, COR_REPRESENTACAO, PRIORIDADE_NUMERICA, ACOES_RECOMENDADAS) 
VALUES ('BAIXO', 'Risco baixo - situação sob controle', '#28a745', 1, 'Monitoramento de rotina');

INSERT INTO GS_WW_NIVEL_SEVERIDADE (CODIGO_SEVERIDADE, DESCRICAO_SEVERIDADE, COR_REPRESENTACAO, PRIORIDADE_NUMERICA, ACOES_RECOMENDADAS) 
VALUES ('MEDIO', 'Risco médio - atenção necessária', '#ffc107', 2, 'Aumentar frequência de monitoramento');

INSERT INTO GS_WW_NIVEL_SEVERIDADE (CODIGO_SEVERIDADE, DESCRICAO_SEVERIDADE, COR_REPRESENTACAO, PRIORIDADE_NUMERICA, ACOES_RECOMENDADAS) 
VALUES ('ALTO', 'Risco alto - medidas preventivas', '#fd7e14', 3, 'Alertar população, preparar equipes');

INSERT INTO GS_WW_NIVEL_SEVERIDADE (CODIGO_SEVERIDADE, DESCRICAO_SEVERIDADE, COR_REPRESENTACAO, PRIORIDADE_NUMERICA, ACOES_RECOMENDADAS) 
VALUES ('CRITICO', 'Risco crítico - ação imediata', '#dc3545', 4, 'Evacuação, mobilizar recursos');

INSERT INTO GS_WW_NIVEL_SEVERIDADE (CODIGO_SEVERIDADE, DESCRICAO_SEVERIDADE, COR_REPRESENTACAO, PRIORIDADE_NUMERICA, ACOES_RECOMENDADAS) 
VALUES ('EMERGENCIA', 'Emergência - desastre iminente', '#6f42c1', 5, 'Evacuação imediata, estado de emergência');

-- Inserindo Níveis de Degradação do Solo
INSERT INTO GS_WW_NIVEL_DEGRADACAO_SOLO (CODIGO_DEGRADACAO, DESCRICAO_DEGRADACAO, NIVEL_NUMERICO, CAPACIDADE_ABSORCAO_PERCENTUAL, ACOES_CORRETIVAS, COR_INDICADORA) 
VALUES ('EXCELENTE', 'Solo em excelente estado - alta capacidade de absorção', 1, 95.0, 'Manter práticas sustentáveis atuais', '#28a745');

INSERT INTO GS_WW_NIVEL_DEGRADACAO_SOLO (CODIGO_DEGRADACAO, DESCRICAO_DEGRADACAO, NIVEL_NUMERICO, CAPACIDADE_ABSORCAO_PERCENTUAL, ACOES_CORRETIVAS, COR_INDICADORA) 
VALUES ('BOM', 'Solo em bom estado - boa capacidade de absorção', 2, 75.0, 'Rotação de culturas, cobertura vegetal', '#6f9c3d');

INSERT INTO GS_WW_NIVEL_DEGRADACAO_SOLO (CODIGO_DEGRADACAO, DESCRICAO_DEGRADACAO, NIVEL_NUMERICO, CAPACIDADE_ABSORCAO_PERCENTUAL, ACOES_CORRETIVAS, COR_INDICADORA) 
VALUES ('REGULAR', 'Solo com degradação moderada', 3, 50.0, 'Adubo orgânico, controle de erosão', '#ffc107');

INSERT INTO GS_WW_NIVEL_DEGRADACAO_SOLO (CODIGO_DEGRADACAO, DESCRICAO_DEGRADACAO, NIVEL_NUMERICO, CAPACIDADE_ABSORCAO_PERCENTUAL, ACOES_CORRETIVAS, COR_INDICADORA) 
VALUES ('RUIM', 'Solo degradado - baixa absorção', 4, 25.0, 'Recuperação urgente, plantio direto', '#fd7e14');

INSERT INTO GS_WW_NIVEL_DEGRADACAO_SOLO (CODIGO_DEGRADACAO, DESCRICAO_DEGRADACAO, NIVEL_NUMERICO, CAPACIDADE_ABSORCAO_PERCENTUAL, ACOES_CORRETIVAS, COR_INDICADORA) 
VALUES ('CRITICO', 'Solo muito degradado - risco de enchente', 5, 10.0, 'Recuperação intensiva, revegetação', '#dc3545');

-- ============================================================================
-- 4. INSERTS PARA TABELAS PRINCIPAIS
-- ============================================================================

-- Inserindo Produtores Rurais
INSERT INTO GS_WW_PRODUTOR_RURAL (NOME_COMPLETO, CPF_CNPJ, EMAIL, TELEFONE) 
VALUES ('João Silva Santos', '123.456.789-01', 'joao.silva@waterwise.com', '(11) 98765-4321');

INSERT INTO GS_WW_PRODUTOR_RURAL (NOME_COMPLETO, CPF_CNPJ, EMAIL, TELEFONE) 
VALUES ('Maria Oliveira Costa', '987.654.321-02', 'maria.oliveira@waterwise.com', '(11) 97654-3210');

INSERT INTO GS_WW_PRODUTOR_RURAL (NOME_COMPLETO, CPF_CNPJ, EMAIL, TELEFONE) 
VALUES ('Carlos Eduardo Pereira', '456.789.123-03', 'carlos.pereira@waterwise.com', '(11) 96543-2109');

INSERT INTO GS_WW_PRODUTOR_RURAL (NOME_COMPLETO, CPF_CNPJ, EMAIL, TELEFONE) 
VALUES ('Ana Paula Rodrigues', '789.123.456-04', 'ana.rodrigues@waterwise.com', '(11) 95432-1098');

INSERT INTO GS_WW_PRODUTOR_RURAL (NOME_COMPLETO, CPF_CNPJ, EMAIL, TELEFONE) 
VALUES ('Roberto Almeida Filho', '321.654.987-05', 'roberto.almeida@waterwise.com', '(11) 94321-0987');

INSERT INTO GS_WW_PRODUTOR_RURAL (NOME_COMPLETO, CPF_CNPJ, EMAIL, TELEFONE) 
VALUES ('Fernanda Santos Lima', '159.753.468-06', 'fernanda.lima@waterwise.com', '(11) 93210-8765');

-- Inserindo Propriedades Rurais
INSERT INTO GS_WW_PROPRIEDADE_RURAL (ID_PRODUTOR, ID_NIVEL_DEGRADACAO, NOME_PROPRIEDADE, LATITUDE, LONGITUDE, AREA_HECTARES, TIPO_SOLO) 
VALUES (1, 2, 'Fazenda Água Limpa', -23.3180000, -46.2340000, 150.75, 'Latossolo Vermelho');

INSERT INTO GS_WW_PROPRIEDADE_RURAL (ID_PRODUTOR, ID_NIVEL_DEGRADACAO, NOME_PROPRIEDADE, LATITUDE, LONGITUDE, AREA_HECTARES, TIPO_SOLO) 
VALUES (2, 3, 'Sítio Verde Esperança', -23.2910000, -46.1980000, 89.50, 'Argissolo Amarelo');

INSERT INTO GS_WW_PROPRIEDADE_RURAL (ID_PRODUTOR, ID_NIVEL_DEGRADACAO, NOME_PROPRIEDADE, LATITUDE, LONGITUDE, AREA_HECTARES, TIPO_SOLO) 
VALUES (3, 1, 'Fazenda Sustentável', -23.2850000, -46.2670000, 220.30, 'Latossolo Vermelho-Amarelo');

INSERT INTO GS_WW_PROPRIEDADE_RURAL (ID_PRODUTOR, ID_NIVEL_DEGRADACAO, NOME_PROPRIEDADE, LATITUDE, LONGITUDE, AREA_HECTARES, TIPO_SOLO) 
VALUES (4, 4, 'Chácara Boa Vista', -23.2740000, -46.1890000, 45.80, 'Neossolo Quartzarênico');

INSERT INTO GS_WW_PROPRIEDADE_RURAL (ID_PRODUTOR, ID_NIVEL_DEGRADACAO, NOME_PROPRIEDADE, LATITUDE, LONGITUDE, AREA_HECTARES, TIPO_SOLO) 
VALUES (5, 2, 'Fazenda Recanto Verde', -23.2590000, -46.2110000, 178.90, 'Argissolo Vermelho');

INSERT INTO GS_WW_PROPRIEDADE_RURAL (ID_PRODUTOR, ID_NIVEL_DEGRADACAO, NOME_PROPRIEDADE, LATITUDE, LONGITUDE, AREA_HECTARES, TIPO_SOLO) 
VALUES (6, 5, 'Sítio Terra Seca', -23.3050000, -46.2450000, 67.25, 'Solo Degradado');

-- Inserindo Sensores IoT
INSERT INTO GS_WW_SENSOR_IOT (ID_PROPRIEDADE, ID_TIPO_SENSOR, MODELO_DISPOSITIVO, MAC_ADDRESS, BATERIA_NIVEL) 
VALUES (1, 1, 'ESP32-WaterWise-v1', 'AA:BB:CC:DD:EE:01', 87);

INSERT INTO GS_WW_SENSOR_IOT (ID_PROPRIEDADE, ID_TIPO_SENSOR, MODELO_DISPOSITIVO, MAC_ADDRESS, BATERIA_NIVEL) 
VALUES (1, 3, 'ESP32-WaterWise-v1', 'AA:BB:CC:DD:EE:02', 92);

INSERT INTO GS_WW_SENSOR_IOT (ID_PROPRIEDADE, ID_TIPO_SENSOR, MODELO_DISPOSITIVO, MAC_ADDRESS, BATERIA_NIVEL) 
VALUES (2, 1, 'ESP32-WaterWise-v1', 'AA:BB:CC:DD:EE:03', 78);

INSERT INTO GS_WW_SENSOR_IOT (ID_PROPRIEDADE, ID_TIPO_SENSOR, MODELO_DISPOSITIVO, MAC_ADDRESS, BATERIA_NIVEL) 
VALUES (3, 2, 'ESP32-WaterWise-v2', 'AA:BB:CC:DD:EE:04', 95);

INSERT INTO GS_WW_SENSOR_IOT (ID_PROPRIEDADE, ID_TIPO_SENSOR, MODELO_DISPOSITIVO, MAC_ADDRESS, STATUS_OPERACIONAL, BATERIA_NIVEL) 
VALUES (4, 4, 'ESP32-WaterWise-v2', 'AA:BB:CC:DD:EE:05', 'I', 23);

INSERT INTO GS_WW_SENSOR_IOT (ID_PROPRIEDADE, ID_TIPO_SENSOR, MODELO_DISPOSITIVO, MAC_ADDRESS, BATERIA_NIVEL) 
VALUES (5, 5, 'ESP32-WaterWise-v3', 'AA:BB:CC:DD:EE:06', 82);

INSERT INTO GS_WW_SENSOR_IOT (ID_PROPRIEDADE, ID_TIPO_SENSOR, MODELO_DISPOSITIVO, MAC_ADDRESS, BATERIA_NIVEL) 
VALUES (6, 6, 'ESP32-WaterWise-v3', 'AA:BB:CC:DD:EE:07', 67);

-- Inserindo Leituras dos Sensores
INSERT INTO GS_WW_LEITURA_SENSOR (ID_SENSOR, UMIDADE_SOLO, TEMPERATURA_AR, PRECIPITACAO_MM, QUALIDADE_SINAL) 
VALUES (1, 45.5, 22.3, 0.0, 85);

INSERT INTO GS_WW_LEITURA_SENSOR (ID_SENSOR, TEMPERATURA_AR, PRECIPITACAO_MM, QUALIDADE_SINAL) 
VALUES (2, 21.8, 15.2, 90);

INSERT INTO GS_WW_LEITURA_SENSOR (ID_SENSOR, UMIDADE_SOLO, TEMPERATURA_AR, PRECIPITACAO_MM, QUALIDADE_SINAL) 
VALUES (3, 38.2, 23.1, 0.5, 75);

INSERT INTO GS_WW_LEITURA_SENSOR (ID_SENSOR, TEMPERATURA_AR, PRECIPITACAO_MM, QUALIDADE_SINAL) 
VALUES (4, 24.5, 0.0, 88);

INSERT INTO GS_WW_LEITURA_SENSOR (ID_SENSOR, TEMPERATURA_AR, PRECIPITACAO_MM, NIVEL_AGUA_RESERVATORIO, QUALIDADE_SINAL) 
VALUES (5, 22.9, 0.0, 2.35, 45);

INSERT INTO GS_WW_LEITURA_SENSOR (ID_SENSOR, UMIDADE_SOLO, TEMPERATURA_AR, QUALIDADE_SINAL) 
VALUES (6, 28.7, 25.1, 72);

INSERT INTO GS_WW_LEITURA_SENSOR (ID_SENSOR, UMIDADE_SOLO, TEMPERATURA_AR, QUALIDADE_SINAL) 
VALUES (7, 18.3, 26.8, 58);

-- Inserindo Áreas de Risco Urbana (Mairiporã/SP)
INSERT INTO GS_WW_AREA_RISCO_URBANA (NOME_AREA, CIDADE, BAIRRO, LATITUDE_CENTRO, LONGITUDE_CENTRO, RAIO_INFLUENCIA_KM, POPULACAO_AFETADA, NIVEL_RISCO) 
VALUES ('Vila Nova Mairiporã', 'Mairiporã', 'Vila Nova', -23.3180000, -46.5870000, 2.5, 1200, 4);

INSERT INTO GS_WW_AREA_RISCO_URBANA (NOME_AREA, CIDADE, BAIRRO, LATITUDE_CENTRO, LONGITUDE_CENTRO, RAIO_INFLUENCIA_KM, POPULACAO_AFETADA, NIVEL_RISCO) 
VALUES ('Jardim Inconfidência', 'Mairiporã', 'Jardim Inconfidência', -23.3250000, -46.5980000, 1.8, 850, 3);

INSERT INTO GS_WW_AREA_RISCO_URBANA (NOME_AREA, CIDADE, BAIRRO, LATITUDE_CENTRO, LONGITUDE_CENTRO, RAIO_INFLUENCIA_KM, POPULACAO_AFETADA, NIVEL_RISCO) 
VALUES ('Centro Histórico', 'Mairiporã', 'Centro', -23.3210000, -46.5860000, 3.2, 2100, 5);

INSERT INTO GS_WW_AREA_RISCO_URBANA (NOME_AREA, CIDADE, BAIRRO, LATITUDE_CENTRO, LONGITUDE_CENTRO, RAIO_INFLUENCIA_KM, POPULACAO_AFETADA, NIVEL_RISCO) 
VALUES ('Parque das Nações', 'Mairiporã', 'Parque das Nações', -23.3090000, -46.5730000, 2.1, 980, 2);

INSERT INTO GS_WW_AREA_RISCO_URBANA (NOME_AREA, CIDADE, BAIRRO, LATITUDE_CENTRO, LONGITUDE_CENTRO, RAIO_INFLUENCIA_KM, POPULACAO_AFETADA, NIVEL_RISCO) 
VALUES ('Vila Albertina', 'Mairiporã', 'Vila Albertina', -23.3340000, -46.6010000, 1.5, 675, 3);

INSERT INTO GS_WW_AREA_RISCO_URBANA (NOME_AREA, CIDADE, BAIRRO, LATITUDE_CENTRO, LONGITUDE_CENTRO, RAIO_INFLUENCIA_KM, POPULACAO_AFETADA, NIVEL_RISCO) 
VALUES ('Distrito Industrial', 'Mairiporã', 'Distrito Industrial', -23.2980000, -46.5920000, 2.8, 450, 4);

-- Inserindo Alertas
INSERT INTO GS_WW_ALERTA (ID_AREA_RISCO, ID_NIVEL_SEVERIDADE, DESCRICAO_ALERTA, PREVISAO_INICIO, PREVISAO_FIM, USUARIO_CRIACAO) 
VALUES (1, 3, 'Previsão de chuva forte nas próximas 6 horas', CURRENT_TIMESTAMP + INTERVAL '2' HOUR, CURRENT_TIMESTAMP + INTERVAL '8' HOUR, 'sistema_automatico');

INSERT INTO GS_WW_ALERTA (ID_AREA_RISCO, ID_NIVEL_SEVERIDADE, DESCRICAO_ALERTA, PREVISAO_INICIO, PREVISAO_FIM, USUARIO_CRIACAO) 
VALUES (3, 4, 'Solo saturado + previsão de temporal', CURRENT_TIMESTAMP + INTERVAL '1' HOUR, CURRENT_TIMESTAMP + INTERVAL '12' HOUR, 'analista_meteorologia');

INSERT INTO GS_WW_ALERTA (ID_AREA_RISCO, ID_NIVEL_SEVERIDADE, DESCRICAO_ALERTA, TIMESTAMP_ALERTA, STATUS_ALERTA, USUARIO_CRIACAO) 
VALUES (2, 2, 'Monitoramento preventivo', CURRENT_TIMESTAMP - INTERVAL '2' DAY, 'RESOLVIDO', 'tecnico_campo');

INSERT INTO GS_WW_ALERTA (ID_AREA_RISCO, ID_NIVEL_SEVERIDADE, DESCRICAO_ALERTA, TIMESTAMP_ALERTA, STATUS_ALERTA, USUARIO_CRIACAO) 
VALUES (4, 1, 'Chuva moderada prevista', CURRENT_TIMESTAMP - INTERVAL '1' DAY, 'RESOLVIDO', 'sistema_automatico');

INSERT INTO GS_WW_ALERTA (ID_AREA_RISCO, ID_NIVEL_SEVERIDADE, DESCRICAO_ALERTA, PREVISAO_INICIO, PREVISAO_FIM, USUARIO_CRIACAO) 
VALUES (5, 2, 'Acompanhamento de umidade do solo', CURRENT_TIMESTAMP + INTERVAL '4' HOUR, CURRENT_TIMESTAMP + INTERVAL '10' HOUR, 'supervisor_regional');

INSERT INTO GS_WW_ALERTA (ID_AREA_RISCO, ID_NIVEL_SEVERIDADE, DESCRICAO_ALERTA, USUARIO_CRIACAO) 
VALUES (6, 5, 'Emergência: solo crítico + chuva torrencial', 'coordenador_emergencia');